name: Test Examples

on:
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install lex and yacc
      run: |
        sudo apt-get update
        sudo apt-get install -y bison flex
    - name: Run Test 
      run: |
        python __test__/test.py
